services:
  mssql-db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql-db
      ports: 
        - "1434:1433"
      environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
        MSSQL_PID: ${MSSQL_PID:-Developer}
      volumes:
        - mssql-data:/var/opt/mssql
        - ./database:/var/opt/sqlserver/backup
      restart: always

  mssql-init:
      image: mcr.microsoft.com/mssql-tools
      depends_on:
        - mssql-db
      environment:
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      volumes:
        - ./database/init.sql:/scripts/init.sql:ro
      command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P "${MSSQL_SA_PASSWORD}" -i /scripts/init.sql; do echo "Waiting for SQL Server..."; sleep 5; done; echo "Database initialization completed."'

volumes:
  mssql-data: